// GENERATED by tools/docs-capture.mjs. Do not edit by hand.
//
// Intrinsic pixel size of every screenshot in public/docs, so <Figure/>
// can hand next/image a width and height without importing each file.

export type ShotName = keyof typeof SHOTS;

export const SHOTS = {
  "01-signup": { width: 2880, height: 1800 },
  "02-login": { width: 2880, height: 1800 },
  "03-personal-dashboard-empty": { width: 2880, height: 1800 },
  "04-workspace-switcher-empty": { width: 2880, height: 1800 },
  "05-create-workspace": { width: 2880, height: 1800 },
  "06-tour-step-1": { width: 2880, height: 1800 },
  "07-tour-step-2": { width: 2880, height: 1800 },
  "08-tour-step-3": { width: 2880, height: 1800 },
  "09-business-dashboard-empty": { width: 2880, height: 1800 },
  "10-business-dashboard": { width: 2880, height: 1800 },
  "11-workspace-switcher": { width: 2880, height: 1800 },
  "12-approvals": { width: 2880, height: 1800 },
  "14-members": { width: 2880, height: 1800 },
  "15-invite-someone": { width: 2880, height: 1800 },
  "16-add-contract": { width: 2880, height: 3472 },
  "17-contract-detail": { width: 2880, height: 1800 },
  "18-treasury": { width: 2880, height: 2046 },
  "19-log-income": { width: 2880, height: 1800 },
  "20-requests": { width: 2880, height: 1800 },
  "21-request-detail": { width: 2880, height: 1800 },
  "22-create-request": { width: 2880, height: 2526 },
  "23-settings-profile": { width: 2880, height: 1800 },
  "24-settings-wallets": { width: 2880, height: 1800 },
  "25-settings-settlement": { width: 2880, height: 1800 },
  "26-mobile-dashboard": { width: 780, height: 1688 },
  "27-mobile-approvals": { width: 780, height: 1688 },
  "28-invite-landing": { width: 2880, height: 1800 },
  "29-sign-contract": { width: 2880, height: 2118 },
  "30-pay-link": { width: 2880, height: 1800 },
  "31-pay-link-share": { width: 2880, height: 1800 },
  "32-member-view": { width: 2880, height: 1800 },
  "33-notifications-invite": { width: 2880, height: 1800 },
  "34-settings-display": { width: 2880, height: 1800 },
} as const;
