import type { Metadata } from "next";
import { Instrument_Sans, DM_Sans, DM_Mono } from "next/font/google";
import "./globals.css";
import { ClientLayout } from "./client-layout";

// This metadata is the link preview every shared /pay/<token> link renders in
// chat apps — i.e. the first thing a non-user ever sees of the product. It must
// describe requesting money, never splitting.
// See .specs/2026-08-06-request-money-design.md → "Rules that protect the framing".
const SITE_NAME = "Splito";
const TITLE = "Splito — Request money in any currency";
const DESCRIPTION =
  "Ask for money in the currency you think in. Get paid in the one you want. Send a link — no signup, no install.";
const SITE_URL = process.env.NEXT_PUBLIC_FRONTEND_URL || "https://app.splito.io";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: { default: TITLE, template: `%s · ${SITE_NAME}` },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: TITLE,
    description: DESCRIPTION,
    url: "/",
  },
  // The image itself is generated by app/opengraph-image.tsx — Next.js wires it
  // into both the og: and twitter: tags automatically, so no url is set here.
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
  variable: "--font-dm-sans",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
  variable: "--font-dm-mono",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${dmSans.variable} ${dmMono.variable}`}>
      <body className={instrumentSans.className}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
