import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Instrument_Sans, DM_Sans, DM_Mono } from "next/font/google";
import "./globals.css";
import { ClientLayout } from "./client-layout";
import { WORKSPACE_COOKIE } from "@/lib/workspace";
import { getSessionCookieValue } from "@/lib/middleware-session";

// This metadata is the link preview every shared /pay/<token> link renders in
// chat apps — i.e. the first thing a non-user ever sees of the product. It must
// describe requesting money, never splitting.
// See .specs/2026-08-06-request-money-design.md → "Rules that protect the framing".
const SITE_NAME = "Splito";
const TITLE = "Splito — Request money in any currency";
const DESCRIPTION =
  "Ask for money in the currency you think in. Get paid in the one you want. Send a link — no signup, no install.";
const SITE_URL = process.env.NEXT_PUBLIC_FRONTEND_URL || "https://app.splito.io";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: { default: TITLE, template: `%s · ${SITE_NAME}` },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: TITLE,
    description: DESCRIPTION,
    url: "/",
  },
  // The image itself is generated by app/opengraph-image.tsx — Next.js wires it
  // into both the og: and twitter: tags automatically, so no url is set here.
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
  variable: "--font-dm-sans",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
  variable: "--font-dm-mono",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Read the active workspace here so the server render and the first client
  // render agree on which workspace is showing. See contexts/workspace.tsx.
  const cookieStore = await cookies();
  const activeWorkspaceId = cookieStore.get(WORKSPACE_COOKIE)?.value ?? null;

  // The better-auth session cookie is httpOnly, so the client can never tell a
  // signed-out visitor from a signed-in one before GET /api/users/me answers —
  // which is why "/" fired that request (and 401'd) for every anonymous
  // visitor. Read it here, where it IS readable, and pass the answer down.
  // Presence only, never trusted as authentication: the server still validates
  // on every request. See lib/middleware-session.ts for the canonical names.
  const hasSession = getSessionCookieValue((name) => cookieStore.get(name)?.value) !== null;

  return (
    <html lang="en" className={`${dmSans.variable} ${dmMono.variable}`}>
      <body className={instrumentSans.className}>
        <ClientLayout initialWorkspaceId={activeWorkspaceId} hasSession={hasSession}>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
